---
apiVersion: v2
appVersion: "0.2.0"
description: Helm chart to deploy and manage MongoDB operator in Kubernetes.
engine: gotpl
maintainers:
  - name: Abhishek Dubey
  - name: Sandeep Rawat
name: mongodb-operator
sources:
  - https://github.com/OT-CONTAINER-KIT/mongodb-operator
version: 0.2.0
home: https://github.com/OT-CONTAINER-KIT/mongodb-operator
icon: https://raw.githubusercontent.com/OT-CONTAINER-KIT/mongodb-operator/main/static/mongodb-operator-logo.svg
keywords:
- operator
- mongodb
- opstree
- kubernetes
- openshift
- backup
- restore
- mongodb-cluster
