{{- if eq .Values.externalConfig.enabled true }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ext-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: middleware
    app.kubernetes.io/part-of : {{ .Release.Name }}
data:
  redis-additional.conf: |
    {{ .Values.externalConfig.data | nindent 4 }}
{{- end }}
