{{- if eq .Values.externalService.enabled true }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-leader-external-service
{{- if .Values.externalService.annotations }}
  annotations:
{{ toYaml .Values.externalService.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: middleware
spec:
  type: {{ .Values.externalService.serviceType }}
  selector:
    app: {{ .Release.Name }}-leader
    redis_setup_type: leader
    role: leader
  ports:
    - protocol: TCP
      port: {{ .Values.externalService.port }}
      targetPort: 6379
      name: client
{{- end }}
