apiVersion: v2
name: microservice
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
maintainers:
  - name: Shikha Tripathi
    email: shikha.tripathi@mygurukulam.co
