apiVersion: v2
name: microservice
description: Basic helm chart for deploying microservices on kubernetes with best practices
type: application
version: 0.1.3
appVersion: "0.1.2"
maintainers:
  - name: Ashwani Singh
    email: ashwani.singh@opstree.com
  - name: Shikha Tripathi
