apiVersion: v2
name: opentelemetry-operator
description: A Helm chart for Opentelemetry Operator
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: opentelemetry-operator
    version: 0.64.2
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts/
    alias: operator
    tags:
      - operator
    condition: operator.enabled
