base:
  image:
    pullPolicy: "Always"
    command: ["./gitguard-consumer", "events"]
    repository:  registry.ldc.opstree.dev/sentryfuse/gitguard-consumer
    tag: latest
    pullSecrets: "sentryfuse-harbor-secret"
  env:
    - name: FORCE_ROLLOUT
      value: "{{ .Release.Time }}"

replicaCount: 1

healthcheck:
  enabled: false
  statusPath: /health

service:
  type: ClusterIP
  port: 8080

resources: {}

volumes:
  configMaps:
    - name: gitguard-consumer-config
      mountPath: /etc/gitguard/
      data:
        config.yaml: |
          kafka:
            brokers: [""]

          postgres:
            addr: ""
            user: "postgres"
            password: "password"
            dbname: "git_guard"

          pagerduty:
            enabled: true

          slack:
            enabled: true
            channel_id: C08L2MYFVCH

          rules:
            - regex: |-
                (A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}
              description: "AWS Access Key"
              tags: ["key", "AWS"]
              entropy: 4.06

            - regex: |-
                (?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]
              description: "AWS Secret Key"
              tags: ["key", "AWS"]
              entropy: 4.06

livenessProbe: {}
readinessProbe: {}

ingress:
  enabled: false

internalIngress:
  enabled: false

autoscaling:
  enabled: false
