apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-loki-datasource
  labels:
    grafana_datasource: "1"
    app: kube-grafana
    prometheus: kube
data:
  kube-loki.yaml: |-
    apiVersion: 1
    datasources:
      - uid: logging
        orgId: 1
        name: logging
        type: loki
        typeName: Loki
        access: proxy
        url: http://logging-loki-gateway.logging.svc.cluster.local
        password: ''
        user: ''
        database: ''
        basicAuth: false
        isDefault: false
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: (?:trace_id)=(\w+)
              name: TraceID
              url: $${__value.raw}
        readOnly: false
        editable: true
