apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-datasource
  labels:
    grafana_datasource: "1"
    app: kube-grafana
    prometheus: kube
data:
  kube-prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: "kube-prom"
        type: prometheus
        uid: prometheus
        url: http://kube-prometheus.monitoring:9090/
        access: proxy
        isDefault: true
        jsonData:
          httpMethod: POST
          timeInterval: 30s
          exemplarTraceIdDestinations:
            - datasourceUid: tempo
              name: TraceID
        readOnly: false
        editable: true
