---
apiVersion: v1
description: Provides easy mongodb setup definitions for Kubernetes services, and deployment.
engine: gotpl
maintainers:
  - name: Opstree Solutions
name: mongodb
sources:
  - https://github.com/ot-container-kit/mongodb-operator
version: 0.2.0
appVersion: "0.2.0"
home: https://github.com/ot-container-kit/mongodb-operator
keywords:
- operator
- MongoDB
- opstree
- kubernetes
- openshift
- mongodb-exporter
icon: https://github.com/OT-CONTAINER-KIT/mongodb-operator/raw/main/static/mongodb-operator-logo.svg
