---
image:
  name: quay.io/opstree/mongo
  tag: v5.0.6
  imagePullPolicy: IfNotPresent
  # pullSecret: regcred

nodeSelector: {}
#  memory: high

#priorityClassName: "-"

securityContext:
  fsGroup: 1001

affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: disktype
  #         operator: In
  #         values:
  #         - ssd

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

tolerations: []
#  - key: "example-key"
#    operator: "Exists"
#    effect: "NoSchedule"

storage:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  storageSize: 1Gi
  storageClass:

mongoDBSecurity:
  mongoDBAdminUser: admin
  mongoDBPassword: password  

mongoDBMonitoring:
  enabled: false
  image:
    name: bitnami/mongodb-exporter
    tag: 0.11.2-debian-10-r382
    imagePullPolicy: IfNotPresent
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

#mongoDBConfiguration: |-
#  net:
#    bindIp: 0.0.0.0
#    port: 27017

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring
