---
apiVersion: v1
description: Provides easy setup of vault webhook inside Kubernetes cluster
engine: gotpl
maintainers:
  - name: Opstree Solutions
name: k8s-vault-webhook
sources:
  - https://github.com/opstree/k8s-vault-webhook
version: "0.2"
home: https://github.com/opstree/k8s-vault-webhook
keywords:
- vault
- kubernetes
- webhook
- security
- secret-manager
icon: https://vectr.com/iamabhishek-dubey/cdDqkelIy.svg?width=183.33&height=190.51&select=adu1SDnVV,b2k1geAiEE,bDWOWW7bs,b1ZDhIHlP1&source=selection
