apiVersion: v2
name: pg-operator-db
description: A Helm chart for Percona Operator and Percona Distribution for PostgreSQL
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: pg-operator
    version: 2.5.0
    repository: https://percona.github.io/percona-helm-charts/
    alias: pg-operator
    tags:
      - pg-operator
    condition: pg-operator.enabled
  - name: pg-db
    version: 2.5.1
    repository: https://percona.github.io/percona-helm-charts/
    alias: pg-db
    tags:
      - pg-db
    condition: pg-db.enabled
