---
apiVersion: v2
appVersion: "0.14.0"
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
engine: gotpl
maintainers:
  - name: iamabhishek-dubey
  - name: sandy724
name: redis-operator
sources:
  - https://github.com/OT-CONTAINER-KIT/redis-operator
version: 0.14.1
home: https://github.com/OT-CONTAINER-KIT/redis-operator
icon: https://github.com/OT-CONTAINER-KIT/redis-operator/raw/master/static/redis-operator-logo.svg
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
