{{- if .Values.secret.enabled }}
---
 apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
        {{- include "base.labels" $ | nindent 4 }}
stringData:
  {{- toYaml .Values.secret | nindent 2 -}}
{{- end }}
