{{- if .Values.global.pdb }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.global.name.appName }}
  labels:
    {{- toYaml .Values.global.name.appLabel | nindent 8 }}
spec:
  minAvailable: {{ .Values.global.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- toYaml .Values.global.name.appLabel | nindent 8 }}
{{- end }}
