---
apiVersion: v2
description: A deployment helm chart which will be used to deploy any type of stateless application
maintainers:
  - name: iamabhishek-dubey
    email: "abhishek.dubey@opstree.com"
    url: https://github.com/iamabhishek-dubey
name: worker
sources:
  - https://github.com/ot-container-kit/helm-charts
dependencies:
  - name: base
    version: 0.1.0
    repository: https://ot-container-kit.github.io/helm-charts
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/ot-container-kit/helm-charts
keywords:
  - deployment
  - base
  - opstree
  - kubernetes
  - openshift
  - microservice
  - stateless
icon: https://raw.githubusercontent.com/OT-CONTAINER-KIT/helm-charts/main/static/helm-chart-logo.svg
